### ISSUE TITLE
train，error：launch.py: error: argument --nproc_per_node: invalid int value: ''

### ISSUE THREAD

**Issue by ZYK266139** [kemaloksuz/aLRPLoss#6]
launch.py: error: argument --nproc_per_node: invalid int value: ''

**Comment by kemaloksuz** [comment]
It seems it is a parsing error related to the training command. Please make sure that you specify an integer as Number of gpus. To illustrate, it is 4 in the example below: 

./tools/dist_train.sh configs/alrp_loss/alrp_loss_retinanet_r50_fpn_ATSS_100e_coco500.py 4

**Comment by ZYK266139** [comment]
Hello author, because I only have one GPU. After executing the training command, the following error occurred.I need your help.








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kemaloksuz/aLRPLoss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 下午3:29
收件人:&nbsp;"kemaloksuz/aLRPLoss"<aLRPLoss@noreply.github.com&gt;;
抄送:&nbsp;"风闻有你"<1326670850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kemaloksuz/aLRPLoss] train，error：launch.py: error: argument --nproc_per_node: invalid int value: '' (#6)





 
It seems it is a parsing error related to the training command. Please make sure that you specify an integer as Number of gpus. To illustrate, it is 4 in the example below:
 
./tools/dist_train.sh configs/alrp_loss/alrp_loss_retinanet_r50_fpn_ATSS_100e_coco500.py 4

**Comment by kemaloksuz** [comment]
Hi. If you have one GPU, then you can try the following commands (both should work):

python tools/train.py configs/alrp_loss/alrp_loss_retinanet_r50_fpn_ATSS_100e_coco500.py

./tools/dist_train.sh configs/alrp_loss/alrp_loss_retinanet_r50_fpn_ATSS_100e_coco500.py 1

In this case, if 8 images/gpu causes a memory error, then you can decrease it from the following line:

https://github.com/kemaloksuz/aLRPLoss/blob/5a2c25f49da296d5b876374a856c212dc66c4033/configs/_base_/datasets/coco500_detection_augm.py#L45

**Comment by ZYK266139** [comment]
Thank you for your patient answer. The above question has been solved by referring to your answer, but the error shown in the figure below occurred during training. I check the corresponding registry. There is&nbsp; the keyword. Looking forward to your reply！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kemaloksuz/aLRPLoss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 下午5:00
收件人:&nbsp;"kemaloksuz/aLRPLoss"<aLRPLoss@noreply.github.com&gt;;
抄送:&nbsp;"风闻有你"<1326670850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kemaloksuz/aLRPLoss] train，error：launch.py: error: argument --nproc_per_node: invalid int value: '' (#6)





 
Hi. If you have one GPU, then you can try the following commands (both should work):
 
python tools/train.py configs/alrp_loss/alrp_loss_retinanet_r50_fpn_ATSS_100e_coco500.py
 
./tools/dist_train.sh configs/alrp_loss/alrp_loss_retinanet_r50_fpn_ATSS_100e_coco500.py 1
 
In this case, if 8 images/gpu causes a memory error, then you can decrease it from the following line:
 
https://github.com/kemaloksuz/aLRPLoss/blob/5a2c25f49da296d5b876374a856c212dc66c4033/configs/_base_/datasets/coco500_detection_augm.py#L45

**Comment by kemaloksuz** [comment]
Unfortunately, I can not see any figure depicting the error.

**Comment by ZYK266139** [comment]
Sorry, I don’t know why the picture is not displayed correctly, I will send it again, thank you for your patience!










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kemaloksuz/aLRPLoss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 晚上7:15
收件人:&nbsp;"kemaloksuz/aLRPLoss"<aLRPLoss@noreply.github.com&gt;;
抄送:&nbsp;"风闻有你"<1326670850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kemaloksuz/aLRPLoss] train，error：launch.py: error: argument --nproc_per_node: invalid int value: '' (#6)





 
Unfortunately, I can not see any figure depicting the error.

**Comment by ZYK266139** [comment]
Hello, in order to prevent the situation that the picture cannot be received again, I pasted the error into the file!
The following is the error log!

Traceback (most recent call last):
&nbsp; File "tools/train.py", line 153, in <module&gt;
&nbsp;&nbsp;&nbsp; main()
&nbsp; File "tools/train.py", line 126, in main
&nbsp;&nbsp;&nbsp; cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
&nbsp; File "/home/wj/mmdetection/mmdet/models/builder.py", line 67, in build_detector
&nbsp;&nbsp;&nbsp; return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
&nbsp; File "/home/wj/mmdetection/mmdet/models/builder.py", line 32, in build
&nbsp;&nbsp;&nbsp; return build_from_cfg(cfg, registry, default_args)
&nbsp; File "/root/anaconda3/envs/FoveaBox/lib/python3.7/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
&nbsp;&nbsp;&nbsp; return obj_cls(**args)
&nbsp; File "/home/wj/mmdetection/mmdet/models/detectors/fovea.py", line 17, in __init__
&nbsp;&nbsp;&nbsp; test_cfg, pretrained)
&nbsp; File "/home/wj/mmdetection/mmdet/models/detectors/single_stage.py", line 30, in __init__
&nbsp;&nbsp;&nbsp; self.bbox_head = build_head(bbox_head)
&nbsp; File "/home/wj/mmdetection/mmdet/models/builder.py", line 57, in build_head
&nbsp;&nbsp;&nbsp; return build(cfg, HEADS)
&nbsp; File "/home/wj/mmdetection/mmdet/models/builder.py", line 32, in build
&nbsp;&nbsp;&nbsp; return build_from_cfg(cfg, registry, default_args)
&nbsp; File "/root/anaconda3/envs/FoveaBox/lib/python3.7/site-packages/mmcv/utils/registry.py", line 164, in build_from_cfg
&nbsp;&nbsp;&nbsp; f'{obj_type} is not in the {registry.name} registry')
KeyError: 'aLRPLossFoveaHead is not in the head registry'





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kemaloksuz/aLRPLoss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 晚上7:15
收件人:&nbsp;"kemaloksuz/aLRPLoss"<aLRPLoss@noreply.github.com&gt;;
抄送:&nbsp;"风闻有你"<1326670850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kemaloksuz/aLRPLoss] train，error：launch.py: error: argument --nproc_per_node: invalid int value: '' (#6)





 
Unfortunately, I can not see any figure depicting the error.

**Comment by kemaloksuz** [comment]
In fact, it is in the registry:

https://github.com/kemaloksuz/aLRPLoss/blob/5a2c25f49da296d5b876374a856c212dc66c4033/mmdet/models/dense_heads/__init__.py#L25

Did you build this repo using:

python setup.py develop

**Comment by ZYK266139** [comment]
Sorry, I encountered another error that I couldn't solve. I installed mmdetection according to the official website, but the following problems occurred. I would like to ask you, what is the positional relationship between mmdetection and aLRPLoss-master? I put aLRPLoss-master under the root directory of the mmdection folder~


(fovealoss) [root@slave2 mmdetection]# python tools/train.py configs/alrp_loss/alrp_loss_fovea_r50_fpn_4x4_100e_coco500.py 
Traceback (most recent call last):
&nbsp; File "tools/train.py", line 15, in <module&gt;
&nbsp;&nbsp;&nbsp; from mmdet.apis import set_random_seed, train_detector
&nbsp; File "/home/wj/aLRPLoss-master/mmdetection/mmdet/apis/__init__.py", line 1, in <module&gt;
&nbsp;&nbsp;&nbsp; from .inference import (async_inference_detector, inference_detector,
&nbsp; File "/home/wj/aLRPLoss-master/mmdetection/mmdet/apis/inference.py", line 7, in <module&gt;
&nbsp;&nbsp;&nbsp; from mmcv.ops import RoIPool
&nbsp; File "/root/anaconda3/envs/fovealoss/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module&gt;
&nbsp;&nbsp;&nbsp; from .box_iou_rotated import box_iou_rotated
&nbsp; File "/root/anaconda3/envs/fovealoss/lib/python3.7/site-packages/mmcv/ops/box_iou_rotated.py", line 5, in <module&gt;
&nbsp;&nbsp;&nbsp; ext_module = ext_loader.load_ext('_ext', ['box_iou_rotated'])
&nbsp; File "/root/anaconda3/envs/fovealoss/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
&nbsp;&nbsp;&nbsp; assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: box_iou_rotated miss in module _ext









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kemaloksuz/aLRPLoss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 晚上7:36
收件人:&nbsp;"kemaloksuz/aLRPLoss"<aLRPLoss@noreply.github.com&gt;;
抄送:&nbsp;"风闻有你"<1326670850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kemaloksuz/aLRPLoss] train，error：launch.py: error: argument --nproc_per_node: invalid int value: '' (#6)





 
In fact, it is in the registry:
 
https://github.com/kemaloksuz/aLRPLoss/blob/5a2c25f49da296d5b876374a856c212dc66c4033/mmdet/models/dense_heads/__init__.py#L25
 
Did you build this repo using:
 
python setup.py develop

**Comment by kemaloksuz** [comment]
This repo is more or less a duplicate one of mmdetection 2.1. However, currently, mmdetection has a newer version (should be 2.6). That's why, some properties could be incompatible.
 
Upon your request, I have updated the instructions in our installation file. I do not expect any problem if the repo is installed following these instructions. Could you please check the following file:

https://github.com/kemaloksuz/aLRPLoss/blob/master/docs/install.md

**Comment by ZYK266139** [comment]
Hello, I also want to ask you, what is the positional relationship between the mmdetection folder and the aLRPLoss-master folder? Thank you very much for your patience!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kemaloksuz/aLRPLoss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 晚上9:43
收件人:&nbsp;"kemaloksuz/aLRPLoss"<aLRPLoss@noreply.github.com&gt;;
抄送:&nbsp;"风闻有你"<1326670850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kemaloksuz/aLRPLoss] train，error：launch.py: error: argument --nproc_per_node: invalid int value: '' (#6)





 
This repo is more or less a duplicate one of mmdetection 2.1. However, currently, mmdetection has a newer version (should be 2.6). That's why, some properties could be incompatible.
 
Upon your request, I have updated the instructions in our installation file. I do not expect any problem if the repo is installed following these instructions. Could you please check the following file:
 
https://github.com/kemaloksuz/aLRPLoss/blob/master/docs/install.md

**Comment by kemaloksuz** [comment]
This repository should be built independent of mmdetection. So, there should not be an "mmdetection" folder. 

If you clone this repository using "git clone https://github.com/kemaloksuz/aLRPLoss.git", then you should find a single folder named as "aLRPLoss" (or maybe aLRPLoss-master in your case). This folder has all you need. Then, you just need to "cd aLRPLoss"  (not "cd mmdetection"). I also corrected this now in installation guideline. Sorry, it was my mistake to mention mmdetection folder previously.

**Comment by ZYK266139** [comment]
Hello, follow the steps on the official website and the related environment configuration requirements. I still encountered a problem in the last step (my environment configuration and the steps performed are in the file), can you please help me to see which aspect of the problem is ?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kemaloksuz/aLRPLoss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 晚上11:47
收件人:&nbsp;"kemaloksuz/aLRPLoss"<aLRPLoss@noreply.github.com&gt;;
抄送:&nbsp;"风闻有你"<1326670850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kemaloksuz/aLRPLoss] train，error：launch.py: error: argument --nproc_per_node: invalid int value: '' (#6)





 
This repository is independent of the mmdetection. So, there should not be an "mmdetection" folder.
 
If you clone this repository using "git clone https://github.com/kemaloksuz/aLRPLoss.git", then you should find a single folder named as "aLRPLoss" (or maybe aLRPLoss-master in your case). This has all you need. Then, just you need to "cd aLRPLoss" instead of "cd mmdetection". I also corrected this now in installation guideline. Sorry, it was my mistake to mention mmdetection folder previously.

**Comment by ZYK266139** [comment]
Hello, I seem to know the problem, where can I download mmdetection2.1, the official website is the latest version 2.7





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kemaloksuz/aLRPLoss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 晚上11:47
收件人:&nbsp;"kemaloksuz/aLRPLoss"<aLRPLoss@noreply.github.com&gt;;
抄送:&nbsp;"风闻有你"<1326670850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kemaloksuz/aLRPLoss] train，error：launch.py: error: argument --nproc_per_node: invalid int value: '' (#6)





 
This repository is independent of the mmdetection. So, there should not be an "mmdetection" folder.
 
If you clone this repository using "git clone https://github.com/kemaloksuz/aLRPLoss.git", then you should find a single folder named as "aLRPLoss" (or maybe aLRPLoss-master in your case). This has all you need. Then, just you need to "cd aLRPLoss" instead of "cd mmdetection". I also corrected this now in installation guideline. Sorry, it was my mistake to mention mmdetection folder previously.

**Comment by kemaloksuz** [comment]
The only repo you need is this one. So, when you follow the steps in [installation guidelines of this repo](https://github.com/kemaloksuz/aLRPLoss/blob/master/docs/install.md) mmdetection2.1 will automatically be installed. For example, the only list of commands that I use to make this repo work is as follows:

conda create -n aLRPLoss python=3.7 -y
conda activate aLRPLoss
conda install pytorch=1.4 torchvision -c pytorch
git clone https://github.com/kemaloksuz/aLRPLoss.git
cd aLRPLoss
pip install -r requirements/build.txt
pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"
python setup.py develop

If you don't have mmcv 0.6 in that environment,  then you also need to install it using "pip install mmcv==0.6". Then, train and test commands should work. So, you do not need to search for mmdetection2.1 elsewhere, installing this repo is sufficient.

**Comment by ZYK266139** [comment]
Hello, when this step "pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"" has a slow download problem (the download source is a foreign problem),how to replace it?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kemaloksuz/aLRPLoss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 中午1:13
收件人:&nbsp;"kemaloksuz/aLRPLoss"<aLRPLoss@noreply.github.com&gt;;
抄送:&nbsp;"风闻有你"<1326670850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kemaloksuz/aLRPLoss] train，error：launch.py: error: argument --nproc_per_node: invalid int value: '' (#6)





 
The only repo you need is this one. So, when you follow the steps in installation guidelines of this repo mmdetection2.1 will automatically be installed. For example, the only list of commands that I use to make this repo work is as follows:
 
conda create -n aLRPLoss python=3.7 -y
 conda activate aLRPLoss
 conda install pytorch=1.4 torchvision -c pytorch
 git clone https://github.com/kemaloksuz/aLRPLoss.git
 cd aLRPLoss
 pip install -r requirements/build.txt
 pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"
 python setup.py develop
 
If you don't have mmcv 0.6 in that environment,  then you also need to install it using "pip install mmcv==0.6". Then, train and test commands should work. So, you do not need to search for mmdetection2.1 elsewhere, installing this repo is sufficient.

**Comment by kemaloksuz** [comment]
It is cocoapi of mmdetection. I can not suggest any replacement but its size should be small.

**Comment by ZYK266139** [comment]
Hello, I executed "pip install mmdet==0.6", and did not download mmdetection separately, and the last step ‘‘python setup.py develop’’ gave the following error：


(alrposs) [root@slave2 aLRPLoss-master]# python setup.py develop
running develop
running egg_info
writing mmdet.egg-info/PKG-INFO
writing dependency_links to mmdet.egg-info/dependency_links.txt
writing requirements to mmdet.egg-info/requires.txt
writing top-level names to mmdet.egg-info/top_level.txt
reading manifest file 'mmdet.egg-info/SOURCES.txt'
writing manifest file 'mmdet.egg-info/SOURCES.txt'
running build_ext
building 'mmdet.ops.utils.compiling_info' extension
gcc -pthread -B /root/anaconda3/envs/alrposs/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I:/usr/local/cuda-10.1/include -fPIC -DWITH_CUDA -I/root/anaconda3/envs/alrposs/lib/python3.7/site-packages/torch/include -I/root/anaconda3/envs/alrposs/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/alrposs/lib/python3.7/site-packages/torch/include/TH -I/root/anaconda3/envs/alrposs/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.1/include -I/root/anaconda3/envs/alrposs/include/python3.7m -c mmdet/ops/utils/src/compiling_info.cpp -o build/temp.linux-x86_64-3.7/mmdet/ops/utils/src/compiling_info.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=compiling_info -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
mmdet/ops/utils/src/compiling_info.cpp:6:30: fatal error: cuda_runtime_api.h: 没有那个文件或目录
compilation terminated.
error: command 'gcc' failed with exit status 1




and execute this command "pip install -v -e." and report this error again, I have a little cras
ERROR: Command errored out with exit status 1: /root/anaconda3/envs/alrposs/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/wj/aLRPLoss-master/setup.py'"'"'; __file__='"'"'/home/wj/aLRPLoss-master/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
&nbsp; File "/root/anaconda3/envs/alrposs/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
&nbsp;&nbsp;&nbsp; status = self.run(options, args)
&nbsp; File "/root/anaconda3/envs/alrposs/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
&nbsp;&nbsp;&nbsp; return func(self, options, args)
&nbsp; File "/root/anaconda3/envs/alrposs/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 403, in run
&nbsp;&nbsp;&nbsp; pycompile=options.compile,
&nbsp; File "/root/anaconda3/envs/alrposs/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 90, in install_given_reqs
&nbsp;&nbsp;&nbsp; pycompile=pycompile,
&nbsp; File "/root/anaconda3/envs/alrposs/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 802, in install
&nbsp;&nbsp;&nbsp; unpacked_source_directory=self.unpacked_source_directory,
&nbsp; File "/root/anaconda3/envs/alrposs/lib/python3.7/site-packages/pip/_internal/operations/install/editable_legacy.py", line 51, in install_editable
&nbsp;&nbsp;&nbsp; cwd=unpacked_source_directory,
&nbsp; File "/root/anaconda3/envs/alrposs/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 240, in call_subprocess
&nbsp;&nbsp;&nbsp; raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /root/anaconda3/envs/alrposs/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/wj/aLRPLoss-master/setup.py'"'"'; __file__='"'"'/home/wj/aLRPLoss-master/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-yjsn1rxk'


I directly execute the training command ''python tools/train.py configs/alrp_loss/alrp_loss_fovea_r50_fpn_4x4_100e_coco500.py and this error occurs again



(alrposs) [root@slave2 aLRPLoss-master]# python tools/train.py configs/alrp_loss/alrp_loss_fovea_r50_fpn_4x4_100e_coco500.py 
/root/anaconda3/envs/alrposs/lib/python3.7/site-packages/mmcv/utils/registry.py:64: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
&nbsp; 'The old API of register_module(module, force=False) '
Traceback (most recent call last):
&nbsp; File "tools/train.py", line 12, in <module&gt;
&nbsp;&nbsp;&nbsp; from mmdet import __version__
ModuleNotFoundError: No module named 'mmdet'




So the execution of this environment depends on mmdetection, mmdetection and alrp are not independent

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kemaloksuz/aLRPLoss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 中午1:13
收件人:&nbsp;"kemaloksuz/aLRPLoss"<aLRPLoss@noreply.github.com&gt;;
抄送:&nbsp;"风闻有你"<1326670850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kemaloksuz/aLRPLoss] train，error：launch.py: error: argument --nproc_per_node: invalid int value: '' (#6)





 
The only repo you need is this one. So, when you follow the steps in installation guidelines of this repo mmdetection2.1 will automatically be installed. For example, the only list of commands that I use to make this repo work is as follows:
 
conda create -n aLRPLoss python=3.7 -y
 conda activate aLRPLoss
 conda install pytorch=1.4 torchvision -c pytorch
 git clone &nbsp;&nbsp;
 cd aLRPLoss
 pip install -r requirements/build.txt
 pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"
 python setup.py develop
 
If you don't have mmcv 0.6 in that environment,  then you also need to install it using "pip install mmcv==0.6". Then, train and test commands should work. So, you do not need to search for mmdetection2.1 elsewhere, installing this repo is sufficient.

**Comment by kemaloksuz** [comment]
"So the execution of this environment depends on mmdetection, mmdetection and alrp are not independent" -> I do not agree. This repo is a copy of mmdetection and runs standalone. The problem is you were not able to install this repo due to some gcc error: 
"error: command 'gcc' failed with exit status 1", and unless you could not complete the installation and build the code, training error is normal since  'mmdet' module is not created yet. I suggest you to solve the gcc error, compile the code first, and then try training.

**Comment by ZYK266139** [comment]
Thank you very much for your patient answers, which helped me successfully run through. I have one last question to ask you about the path setting of the data set and the number of iterations of each epoch set under that folder. Thank you very much and look forward to you 's reply！







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kemaloksuz/aLRPLoss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 下午3:45
收件人:&nbsp;"kemaloksuz/aLRPLoss"<aLRPLoss@noreply.github.com&gt;;
抄送:&nbsp;"风闻有你"<1326670850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kemaloksuz/aLRPLoss] train，error：launch.py: error: argument --nproc_per_node: invalid int value: '' (#6)





 
"So the execution of this environment depends on mmdetection, mmdetection and alrp are not independent" -&gt; I do not agree. This repo is a copy of mmdetection and runs standalone. The problem is you were not able to install this repo due to some gcc error:
 "error: command 'gcc' failed with exit status 1", and unless you could not complete the installation and build the code, training error is normal since  'mmdet' module is not created yet. I suggest you to solve the gcc error, compile the code first, and then try training.

**Comment by kemaloksuz** [comment]
Basically you need a "data" folder under aLRPLoss. For details, You can check [getting started](https://github.com/kemaloksuz/aLRPLoss/blob/master/docs/getting_started.md) file to see the where the data should reside. The root is aLRPLoss, not mmdetection. 

The number of iterations per epoch depends on the image size. It is approximately 3665 iterations with 32 batch size using 512x512 images, and 7330 iterations with 16 batch size using 800x800 images. You can also refer to config files for training details: (e.g. https://github.com/kemaloksuz/aLRPLoss/blob/master/configs/alrp_loss/alrp_loss_retinanet_r50_fpn_ATSS_100e_coco500.py).

**Comment by ZYK266139** [comment]
Hello, I have understood the problem of parameter settings, but now there is a problem, my learning rate is getting higher and higher, I am training my own data set, not the coco dataset, I need your advice, I have learned Rate decreases, batchsize increases！



The following is part of my training log：





2020-12-18 18:40:15,851 - mmdet - INFO - Epoch [2][40/280]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; lr: 1.277e-03, eta: 5:16:31, time: 0.389, data_time: 0.057, memory: 1861, loss_cls: 0.8506, loss_bbox: 3.5001, loss: 4.3507
2020-12-18 18:40:29,113 - mmdet - INFO - Epoch [2][80/280]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; lr: 1.437e-03, eta: 5:15:18, time: 0.332, data_time: 0.004, memory: 1861, loss_cls: 0.7910, loss_bbox: 4.4635, loss: 5.2545
2020-12-18 18:40:42,414 - mmdet - INFO - Epoch [2][120/280]&nbsp;&nbsp;&nbsp;&nbsp; lr: 1.596e-03, eta: 5:14:23, time: 0.333, data_time: 0.004, memory: 1861, loss_cls: 0.7352, loss_bbox: 5.4476, loss: 6.1828
2020-12-18 18:40:55,786 - mmdet - INFO - Epoch [2][160/280]&nbsp;&nbsp;&nbsp;&nbsp; lr: 1.756e-03, eta: 5:13:44, time: 0.334, data_time: 0.004, memory: 1861, loss_cls: 0.7283, loss_bbox: 5.8616, loss: 6.5899
2020-12-18 18:41:09,324 - mmdet - INFO - Epoch [2][200/280]&nbsp;&nbsp;&nbsp;&nbsp; lr: 1.916e-03, eta: 5:13:29, time: 0.338, data_time: 0.004, memory: 1861, loss_cls: 0.7070, loss_bbox: 6.2417, loss: 6.9487
2020-12-18 18:41:22,667 - mmdet - INFO - Epoch [2][240/280]&nbsp;&nbsp;&nbsp;&nbsp; lr: 2.000e-03, eta: 5:12:53, time: 0.334, data_time: 0.004, memory: 1861, loss_cls: 0.6809, loss_bbox: 7.4181, loss: 8.0990
2020-12-18 18:41:35,866 - mmdet - INFO - Epoch [2][280/280]&nbsp;&nbsp;&nbsp;&nbsp; lr: 2.000e-03, eta: 5:12:06, time: 0.330, data_time: 0.004, memory: 1861, loss_cls: 0.6957, loss_bbox: 7.2746, loss: 7.9703

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kemaloksuz/aLRPLoss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 晚上6:22
收件人:&nbsp;"kemaloksuz/aLRPLoss"<aLRPLoss@noreply.github.com&gt;;
抄送:&nbsp;"风闻有你"<1326670850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kemaloksuz/aLRPLoss] train，error：launch.py: error: argument --nproc_per_node: invalid int value: '' (#6)





 
Basically you need a "data" folder under aLRPLoss. For details, You can check getting started file to see the where the data should reside. The root is aLRPLoss, not mmdetection.
 
The number of iterations per epoch depends on the image size. It is approximately 3665 iterations with 32 batch size using 512x512 images, and 7330 iterations with 16 batch size using 800x800 images. You can also refer to config files for training details: (e.g. https://github.com/kemaloksuz/aLRPLoss/blob/master/configs/alrp_loss/alrp_loss_retinanet_r50_fpn_ATSS_100e_coco500.py).

**Comment by ZYK266139** [comment]
Hello, this is my configuration file, I have made some changes, but still can’t stop the loss from getting higher and higher


_base_ = [
    '../_base_/datasets/coco500_detection_augm.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]
dataset_type = 'CocoDataset'
data_root = './data/coco/'
# model settings
model = dict(
    type='FOVEA',
    pretrained='torchvision://resnet101',
    backbone=dict(
        type='ResNet',
        depth=101,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        num_outs=5,
        add_extra_convs='on_input'),
    bbox_head=dict(
        type='aLRPLossFoveaHead',
        num_classes=3,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        strides=[8, 16, 32, 64, 128],
        base_edge_list=[16, 32, 64, 128, 256],
        scale_ranges=((1, 64), (32, 128), (64, 256), (128, 512), (256, 2048)),
        sigma=0.4,
        with_deform=False,
        loss_bbox=dict(type='GIoULoss', reduction='none')))
# training and testing settings
train_cfg = dict()
test_cfg = dict(
    nms_pre=1000,
    score_thr=0.05,
    nms=dict(type='nms', iou_thr=0.5),
    max_per_img=100)

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    to_rgb=True)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(640, 480), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(640, 480),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

data = dict(
    samples_per_gpu=4,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/train.json',
        img_prefix=data_root + 'train/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/val.json',
        img_prefix=data_root + 'val/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/test.json',
        img_prefix=data_root + 'test/',
        pipeline=test_pipeline))




# optimizer
optimizer = dict(type='SGD', lr=0.002, momentum=0.9, weight_decay=0.0001)

# learning policy
lr_config = dict(step=[75, 95])
total_epochs = 200

# yapf:disable
log_config = dict(
    interval=40,
    hooks=[
        dict(type='TextLoggerHook'),
        #dict(type='TensorboardLoggerHook')
    ])

# yapf:enable
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
checkpoint_config = dict(interval=20)
evaluation = dict(interval=1, metric='bbox')






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kemaloksuz/aLRPLoss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 晚上6:22
收件人:&nbsp;"kemaloksuz/aLRPLoss"<aLRPLoss@noreply.github.com&gt;;
抄送:&nbsp;"风闻有你"<1326670850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kemaloksuz/aLRPLoss] train，error：launch.py: error: argument --nproc_per_node: invalid int value: '' (#6)





 
Basically you need a "data" folder under aLRPLoss. For details, You can check getting started file to see the where the data should reside. The root is aLRPLoss, not mmdetection.
 
The number of iterations per epoch depends on the image size. It is approximately 3665 iterations with 32 batch size using 512x512 images, and 7330 iterations with 16 batch size using 800x800 images. You can also refer to config files for training details: (e.g. https://github.com/kemaloksuz/aLRPLoss/blob/master/configs/alrp_loss/alrp_loss_retinanet_r50_fpn_ATSS_100e_coco500.py).

**Comment by kemaloksuz** [comment]
First, the reason why your learning rate increases can be warming up process in the beginning of the training.

As for your loss, I would suggest to check an [example log file](https://drive.google.com/file/d/1blRO6-C2itppoLCKt6q9CQEl8POn4J4q/view). Note that the overall loss also increases in the beginning of the training due to self balancing mechanism in the localisation branch. That's normal. Then, it will decrease. I would suggest tracking classification loss, which is not affected by self balancing, if you do not want to modify logging. As I see, classification loss decreases in your case. If you want to modify logging, then the best way is to print self balance weight and localisation part separately. In that case classification+localisation will be between 0 and 1, depicting aLRP value without self-balance, and you will clearly see that the total loss decreases. We have a plan to change this logging, but I do not know when. In short, have a look at one of our log files to see slightly increasing loss especially in the beginning of the training is not a problem.

Moreover, I can suggest you setting self balancing period. As I see, an epoch takes 280 iterations. So, you can set it to 280 (or maybe the epochs are very short, so 560, indicating 2 epochs, can be also another candidate). An example how to set this period is below:

https://github.com/kemaloksuz/aLRPLoss/blob/2cfaa8ec3150692cca8b085221f1bd8c8c78db8e/mmdet/models/dense_heads/alrp_loss_fovea_head.py#L98

**Comment by ZYK266139** [comment]
Hello, I have successfully solved my problem according to your suggestion. Once again, I would like to express my sincere thanks to you and thank you for your patience. This is of great help to me who is new to deep learning. The model has also successfully run. And it shows good results on my data set, but I also have a question now: how do I view the ap value of each category, I execute the command "python tools/test.py configs/alrp_loss/alrp_loss_fovea_r50_fpn_4x4_100e_coco500.py work_dirs/alrp_loss_fovea_4cox500_f /latest.pth --eval-options'classwise=True' --eval bbox proposal", but it does not appear, only the value of ap appears



Evaluating bbox...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.09s).
Accumulating evaluation results...
DONE (t=0.03s).
Average Precision&nbsp; (AP) @[ IoU=0.50:0.95 | area=&nbsp;&nbsp; all | maxDets=100 ] = 0.635
Average Precision&nbsp; (AP) @[ IoU=0.50&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | area=&nbsp;&nbsp; all | maxDets=100 ] = 0.900
Average Precision&nbsp; (AP) @[ IoU=0.75&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | area=&nbsp;&nbsp; all | maxDets=100 ] = 0.745
Average Precision&nbsp; (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.357
Average Precision&nbsp; (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.619
Average Precision&nbsp; (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.701
Average Recall&nbsp;&nbsp;&nbsp;&nbsp; (AR) @[ IoU=0.50:0.95 | area=&nbsp;&nbsp; all | maxDets=&nbsp; 1 ] = 0.389
Average Recall&nbsp;&nbsp;&nbsp;&nbsp; (AR) @[ IoU=0.50:0.95 | area=&nbsp;&nbsp; all | maxDets= 10 ] = 0.700
Average Recall&nbsp;&nbsp;&nbsp;&nbsp; (AR) @[ IoU=0.50:0.95 | area=&nbsp;&nbsp; all | maxDets=100 ] = 0.704
Average Recall&nbsp;&nbsp;&nbsp;&nbsp; (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.497
Average Recall&nbsp;&nbsp;&nbsp;&nbsp; (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.696
Average Recall&nbsp;&nbsp;&nbsp;&nbsp; (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.754






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "kemaloksuz/aLRPLoss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月19日(星期六) 凌晨1:28
收件人:&nbsp;"kemaloksuz/aLRPLoss"<aLRPLoss@noreply.github.com&gt;;
抄送:&nbsp;"风闻有你"<1326670850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kemaloksuz/aLRPLoss] train，error：launch.py: error: argument --nproc_per_node: invalid int value: '' (#6)





 
First, the reason why your learning rate increases can be warming up process in the beginning of the training.
 
As for your loss, I would suggest to check an example log file. Note that the overall loss also increases in the beginning of the training due to self balancing mechanism in the localisation branch. That's normal. Then, it will decrease. I would suggest tracking classification loss, which is not affected by self balancing, if you do not want to modify logging. As I see, classification loss decreases in your case. If you want to modify logging, then the best way is to print self balance weight and localisation part separately. In that case classification+localisation will be between 0 and 1, depicting aLRP value without self-balance, and you will clearly see that the total loss decreases. We have a plan to change this logging, but I do not know when. In short, have a look at one of our log files to see slightly increasing loss especially in the beginning of the training is not a problem.
 
Moreover, I can suggest you setting self balancing period. As I see, an epoch takes 280 iterations. So, you can set it to 280 (or maybe the epochs are very short, so 560, indicating 2 epochs, can be also another candidate). An example how to set this period is below:
 
https://github.com/kemaloksuz/aLRPLoss/blob/2cfaa8ec3150692cca8b085221f1bd8c8c78db8e/mmdet/models/dense_heads/alrp_loss_fovea_head.py#L98

**Comment by kemaloksuz** [comment]
I'm glad that you are able to train your model. You're welcome.

I have not needed classwise performance, so I do not have an exact answer and I do not know whether classwise option works. As I see there are related issues also in mmdetection. You can find an answer maybe in mmdetection issues. An example is (but not have a good answer):

https://github.com/open-mmlab/mmdetection/issues/473

If you want to do it by yourself: Together with this repo, you initially installed cocoapi of mmdetection. In your environment, you need to locate this file: 
https://github.com/open-mmlab/cocoapi/blob/master/pycocotools/pycocotools/cocoeval.py

Then, after the line below, the results are aggregated over classes, thresholds, recalls, areas and maximum detections, resulting in a single AP. You need to rewrite the code such that you have class-wise scores:

https://github.com/open-mmlab/cocoapi/blob/01f805cd54d7bd7af64c0fbd5fd96d8ca0b9ddc9/pycocotools/pycocotools/cocoeval.py#L476

I think modifying the following line accordingly should work. You need to get mean over all dimensions except classes. 

https://github.com/open-mmlab/cocoapi/blob/01f805cd54d7bd7af64c0fbd5fd96d8ca0b9ddc9/pycocotools/pycocotools/cocoeval.py#L492
